### ISSUE TITLE
NameError: name 'feature' is not defined

### ISSUE THREAD

**Issue by chaimol** [Wangys-prog/prPred#5]
I have installed all the require python packages and other require software. 
I am run `python3 prPred.py -i genome.protein.fa`, have an error 
```
Traceback (most recent call last):
  File "prPred.py", line 11, in <module>
    from codes import *
ImportError: bad magic number in 'codes': b'B\r\r\n'
```
I follow the https://stackoverflow.com/questions/514371/whats-the-bad-magic-number-error,delete the `*.pyc` by run `find . -name '*.pyc' -delete`
And then I rerun the command `python3 prPred.py -i genome.protein.fa`,have another error:
```
Traceback (most recent call last):
  File "/share/home/c/soft/prPred/prPred.py", line 65, in <module>
    main()
  File "/share/home/c/soft/prPred/prPred.py", line 54, in main
    feature.extract_feature(input,output)
NameError: name 'feature' is not defined
```
I am runing in linux and python 3.8.13.

**Comment by Wangys-prog** [comment]
Please  do not delete .pyc files,  and please check the format of your input file

**Comment by chaimol** [comment]
I have reinstall prPred.Then run `python3 prPred.py -h` with error as mentioned before
```
Traceback (most recent call last):
  File "prPred.py", line 11, in <module>
    from codes import *
ImportError: bad magic number in 'codes': b'B\r\r\n'
```

**Comment by Wangys-prog** [comment]
1.  " python 3.7 xxxx/xxxx/prPred/prPred.py -i /xxxx/xxxx/test/test.fasta -o /xxxx/xxxxx/result" Please use python3.7， the .pyc files are compiled using python3.7.   
2. "export PATH=$PATH:/xxxx/xxxx/xxxx/prPred/dist/prPred " "prPred -i /xxxx/xxxx/test/test.fasta -o result", Python Version 3.0 or above
