### ISSUE TITLE
Error WH_x

### ISSUE THREAD

**Issue by SamCT** [Wangys-prog/prPred#6]
Hello,
Thank you for the tool. I haven't been able to complete the test example, I am getting an error related to iFeature. Any insight on this?

Traceback (most recent call last):
  File "/etc/bin/iFeature/iFeature.py", line 55, in <module>
    encodings = eval(myFun)
  File "<string>", line 1, in <module>
  File "/etc/bin/ifeature/iFeature/codes/DDE.py", line 60, in DDE
    tmpCode[j] = (tmpCode[j] - myTM[j]) / math.sqrt(myTV[j])
ZeroDivisionError: float division by zero
etc/bin/prPred/prPred/codes/feature.py:67: FutureWarning: read_table is deprecated, use read_csv
etc/bin/prPred/prPred/codes/feature.py:69: FutureWarning: read_table is deprecated, use read_csv
Traceback (most recent call last):
  File "/local/cluster/lib/python3.7/site-packages/pandas-0.24.1-py3.7-linux-x86_64.egg/pandas/core/indexes/base.py", line 2656,
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'WH_x'

**Comment by Wangys-prog** [comment]
I run /test/test.fasta on my  computer using prPred and found no errors. Please check the input file format or ifeature installation.
